
package org.sample.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.2
 * Wed Aug 24 16:09:18 CEST 2011
 * Generated source version: 2.4.2
 */

@XmlRootElement(name = "getVersion", namespace = "http://ws.sample.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getVersion", namespace = "http://ws.sample.org/")

public class GetVersion {


}

